CFLAGS := -MMD -march=native -Wall -Wextra -Wno-unknown-pragmas
libs := -lm

# .d files are generated by gcc to enable lazy compiles
-include $(wildcard *.d)
MAP_OBJ:=$(patsubst %.c,%.o,$(wildcard *.c))
roll: $(MAP_OBJ)
	gcc -O2 $(CFLAGS) $^ $(libs) -o $@

clean:
	rm -f *.d *.o